### ISSUE TITLE
PLC loses connection to MQTT broker if MQTT broker is restarted 

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [SebastianRau/Codesys2-Mqtt-lib#3]
we've noticed that the PLC is unable to deliver any MQTT messages to the broker if the brokker has been restarted.

Can be reproduced as follows (tested using WAGO 750-881): 

- Send messages to broker

- restart broker (I'm using Mosquitto)

- PLC no more delivers messages until it's restarted. 

Is this a bug or this something that should be catched in the code? 
Thank you for any input!

**Comment by sebastianrau** [comment]
Hi,
looks like a Bug. I`ll check this ins the next days, Actually I dont have PLC to test it.

Regards

**Comment by sebastianrau** [comment]
Fixed.

**Comment by MichielVanwelsenaere** [comment]
confirming fix, tested on WAGO 750-881 with mosquitto. Thank you!
