### ISSUE TITLE
Wago hangs

### ISSUE THREAD

**Issue by sobiso** [SebastianRau/Codesys2-Mqtt-lib#4]
I don't know if you still works on this lib but...
I create subprogram, call from PLC_PRG

`
PROGRAM MQTT
VAR
	M1:MQTT_Client;
	sTopic: STRING := 'channels/../publish/fields/field1/..';
	sPayload: STRING;
	sIP: STRING := '34.232.195.16';
	sClientID: STRING := 'client';
	wPortNumber :WORD := 1883;
	xSubscribe: BOOL;
	xPublish: BOOL;
	xConnected: BOOL;
	T1: TON;
END_VAR
---------
T1(IN:= NOT T1.Q, PT:= t#60s);

IF T1.Q THEN
	xPublish := TRUE;
END_IF

M1(
	sTopic:= sTopic,
	sPayload := sPayload,
	sIP := sIP,
	xPublish := xPublish,
	iPortNumber:= wPortNumber,
	xConnected => xConnected,
	sUsername := 'user',
	sPassword := '..',
);
`

Few times data was successful sended, but right now after download my PLC hangs. Leds MS, NS, IO, USR are blinking and i don't have communication with PLC.

**Comment by sebastianrau** [comment]
Hi Sobisco,
can u give me more info about? Did you changed something. Which PLC do you use?
Sound like a Problem with the Network Libs.

**Comment by sobiso** [comment]
Wago 750-841. I added few modules (input/output) to PLC. How i can test network on PLC? I 'am trying to use http_get but i get error about DNS not resolve.
My libs:
WagoLibEthernet_01.lib 15.3.18
SysLibSockets.lib 5.5.11
Lib_MQTT_Publisher_01.lib 26.9.17
Lib_DebugLogger_01.lib 19.7.17
Util.lib 26.9.14
Standard.lib 8.11.10
SYSLIBCALLBACK.LIB 8.11.10

**Comment by sebastianrau** [comment]
maybe the 841 is capable to open different TCP connections like mqtt and http_get at the same time ...
the controller is kind of legacy ... hasn't that much power ...

**Comment by sobiso** [comment]
I used mqtt or http-get, not both at the same time.

**Comment by sebastianrau** [comment]
Can u send me the project file? Also please the FW Version of your 841

**Comment by sobiso** [comment]
Sent to your github email

**Comment by sobiso** [comment]
Ok i thing that i fixed. Variable sPayload should be 'something' at the start. 
`sPayload: STRING:='0';` and `xPublish: BOOL := FALSE`
@SebastianRau can you add default sPayload to some constant ?

**Comment by sobiso** [comment]
After few days of testing i can confirm that PLC stop hanging. But when my internet connection breaks, i cannot switch any lights. It's look like program is in pause mode or something like that.

**Comment by sebastianrau** [comment]
You should run any Communication Stuff in own Programs on different tasks!
Sync between defferent tasks could be done by global vars
