### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by tuxbox** [SebastianRau/Codesys2-Mqtt-lib#5]
Hi,

when I include the Library I get the following errors:

Implementation des Bausteins 'MQTT_Client'
Fehler 4267: MQTT_Client (42): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (48): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (100): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (101): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (162): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (163): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (193): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen
Fehler 4267: MQTT_Client (194): Ein Funktionsbausteinaufruf muss mit dem Namen einer Instanz beginnen

any clues what might be my mistake? thanks a lot!

**Comment by allardlamberink** [comment]
Make sure you include the Codesys2-DebugMessages library to your project as well. https://github.com/SebastianRau/Codesys2-DebugMessages

**Comment by sebastianrau** [comment]
@tuxbox is it solved now?

**Comment by sebastianrau** [comment]
@tuxbox without any feedback i'll close this issue in a few days

**Comment by sebastianrau** [comment]
@allardlamberink THX for helping out!
